# Mirafold sponsorship configuration.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [amys94fr]
# patreon: # username
# open_collective: # username
# ko_fi: # username
# tidelift: # platform-name/package-name
# community_bridge: # project-name
# liberapay: # username
# issuehunt: # username
# lfx_crowdfunding: # cncf-project-name
# polar: # username
# buy_me_a_coffee: # username
# thanks_dev: # u/gh/username
# custom: # ["https://your-site.com/donate"]
